Added Swipe to Delete feature
multimatum-Team/multimatum pull request #103
Opened 2022-03-30 17:36 UTC by Matathiasq13824

This PR implements deletion of deadlines on the ListView by swiping them on the left or the right and a undo option you have made a mistake by deleting it.

2022-03-30 20:11 UTC, felko requested changes

2022-03-30 21:12 UTC, macintosh1398 reviewed
Looks very good to me. The code is modular and the tests are relevant. With the last changes, the code is clean, so I have nothing to add. But obviously, the tests have to pass to get my approval.

2022-03-30 21:47 UTC, macintosh1398 approved these changes
Now the tests pass, I approve.

2022-03-31 10:05 UTC, felko approved these changes

2022-03-31 10:06 UTC, merged