Add notification features
multimatum-Team/multimatum pull request #41
Opened 2022-03-16 15:31 UTC by LennyDZ

This features add functions to create notifications. There is a temporary UI button that set a notification 1 second after the button is clicked.

We can set the title, description and the time when it'll be triggered.
In order to allow the app to set exact alarm at a given time, I had to add a line to the manifest.xml.

ReminderBroadcastReceiver is a new class that will throw the notification when it receive a signal from AlarmManager.

Not tested yet !

2022-03-16 21:02 UTC, macintosh1398 requested changes
The main functionalities look good. Maybe just pay attention to the details that I mentioned in the comments. The coverage is low but if I understood correctly it is the next step for you right ?

2022-03-17 07:24 UTC, LennyDZ commented on app/src/main/java/com/github/multimatum_team/multimatum/MainActivity.kt
> +        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O){
Yeah sure, since we precise in the build.gradle that the minSDK is 26. I just added this because it is recommended by the dock about notifications

2022-03-17 07:27 UTC, LennyDZ commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="36dp"
it's not, the qr generator is in te left, this one is on the right. But maybe there's a conflict with the scanner button which I'm not sure where it is setup

2022-03-17 07:28 UTC, LennyDZ commented on app/src/main/res/layout/activity_main.xml
> +        android:text="trigger Notif"
Sure, but those are temporary button so it doesn't really matter I think.

2022-03-17 07:31 UTC, LennyDZ commented on app/src/main/java/com/github/multimatum_team/multimatum/MainActivity.kt
> +            val notificationManager = getSystemService(NotificationManager::class.java)
What do you mean exactly ?

2022-03-17 07:31 UTC, LennyDZ commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/button"
I changed this

2022-03-17 10:19 UTC, macintosh1398 commented on app/src/main/java/com/github/multimatum_team/multimatum/MainActivity.kt
> +        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O){
Ok, so if it is recommanded it is ok for me to let it like that

2022-03-17 10:24 UTC, macintosh1398 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="36dp"
Yes you're right, the conflict is with my button. It is exactly there. So maybe put it in the middle (I think there is enough space) for now (we can adapt that later). Or maybe in the top left corner ?

2022-03-17 10:28 UTC, macintosh1398 commented on app/src/main/java/com/github/multimatum_team/multimatum/MainActivity.kt
> +            val notificationManager = getSystemService(NotificationManager::class.java)
I would have put channel.description=description after the next val declaration (val notificationManager = ...) for the clarty and readability of the code. If there is a big chunk of variable declarations, having an action inside can be missed by the other readers, but that's a detail :)

2022-03-17 13:55 UTC, Voxanimus requested changes
It seems to be some conflict with the main, you should fix them

2022-03-17 20:21 UTC, Voxanimus approved these changes

2022-03-17 20:34 UTC, merged